# Generated by Django 2.0 on 2018-04-27 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20180427_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aorder',
            name='ups',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
