# Generated by Django 2.0 on 2018-04-27 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20180427_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='aorder',
            name='Email',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
