# Generated by Django 2.0 on 2018-04-27 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_aorder_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aorder',
            old_name='Email',
            new_name='email',
        ),
    ]
